### ISSUE TITLE
Grunt v1.0.0 is underway

### ISSUE THREAD

**Issue by paazmaya** [jpommerening/grunt-run-task#8]
http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released

How about changing the Grunt dependency to `>=0.4.0` in `package.json`?

**Comment by jpommerening** [comment]
Well, first I should try if it works, right? ;)

Will check that later today, thanks for reporting!

**Comment by paazmaya** [comment]
:grapes: for testing if `1.0.0-rc` works...

**Comment by jpommerening** [comment]
Hi! So much for "later today". I should stop using that phrase.

I tested with Grunt `1.0.0-rc1` and it works fine. However, since `grunt-run-task` exposes the Grunt API, it is possible that someone relies on `grunt-run-task` to expose API parts that are specific to Grunt 0.4. As soon as the Grunt team releases 1.0.0, things would start to fall apart.
I think it's sensible to do major version bump here.

Also, I won't use dependency versions without upper bound (ie `>=0.4.0`) because, once Grunt 2 comes around (if that ever happens) people will get that version without ever updating `grunt-run-task` itself.

Hope you agree. I released `grunt-run-task@1.0.0-rc1`, [dist-tagged](https://docs.npmjs.com/cli/dist-tag#purpose) as `rc1`. I'll strip the `-rc1` suffix once Grunt does the same … plus some arbitrary delay :sweat_smile:

**Comment by paazmaya** [comment]
Of course I agree!
Totally valid points there

**Comment by jpommerening** [comment]
http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released :sparkles:

**Comment by paazmaya** [comment]
:star2:

**Comment by paazmaya** [comment]
Thank you! Waiting for `1.0.0`

**Comment by jpommerening** [comment]
@paazmaya published! Thanks for bringing this to my attention!
